{
 "title": "Contender",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Worker Overall Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (irate(worker_overall_latency_seconds_bucket{}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of retry attempts before COMMIT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (irate(worker_attempts_total_bucket{}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of ROLLBACK TO SAVEPOINT",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (irate(worker_save_point_restarts_total_bucket{}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "flag_info{}", "legendFormat": "{{flag}}" }
   ]
  },
  {
   "title": "Worker Loop Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(worker_overall_latency_seconds_count{}[$__rate_interval]))",
     "legendFormat": "Loop Rate"
    }
   ]
  },
  {
   "title": "DB connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(db_acquired_connection_count)",
     "legendFormat": "Acquired"
    },
    { "expr": "sum(db_idle_connection_count)", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": {
    "content": "This workload operates on a key-value table with some number of concurrent workers.\n\n```sql\nCREATE TABLE IF NOT EXISTS contend (\n\tid UUID NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),\n\tvalue INT NOT NULL DEFAULT 0\n);\n\nBEGIN;\nSELECT value FROM contend WHERE id = $1 [ FOR UPDATE ];\nUPDATE contend SET value = $1 WHERE id = $2;\nCOMMIT;\n```\n"
   }
  },
  {
   "title": "Retryable Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (code) (irate(pgerror_codes_total[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}